apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-service"
spec:
  selector:
    component: {{ .Values.api.name }}
  ports:
    - port: {{ .Values.api.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.cache.name }}-service"
spec:
  selector:
    component: {{ .Values.cache.name}}
  ports:
    - port: {{ .Values.cache.port}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.database.name }}-service"
spec:
  selector:
    component: {{ .Values.database.name }}
  ports:
    - port: {{ .Values.database.port }}
