service:
  type: LoadBalancer
  annotations:
    cloud.google.com/load-balancer-type: "External"
# Set to Recreate if you use persistent volume that cannot be mounted by more than one pods to make sure the pods is destroyed first.
updateStrategy:
  type: Recreate
persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
