
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJYVlLazJ3Y3ppSzB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1ETXhNREF3TURaYUZ3MHpNekV4TXpBeE1EQTFNRFphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURpMUNHVlpKWTU1Vkd3YkhpL1BLVjcxS2pRd0FXVC9wWHhld2xwNVFwcE90MUIvNElKV1FFZ3c5MEEKakFLdERTTisvajlPZnNEQlRjbU1lWU1NUHFyYmgyemRNMEhOMGNYR3d2MkZiUGxLOUdGbmZUa0p0ekhwWWJNdgpjcFlGa2h6VUhoWU90MkpjbEZBZ05DWDI3SlltRVhwa2dBQXlITFpnTVNhdjdMVkh2QnM3QWJXb0V2Q1ljbDBBCnRKYTZCSTM0S3REajVqK00rU2Rrb1N5angvSlVCZHFJYzg0bmwxUjAxR3phRUowVXZHT3NoMzl3S1NzUHNnRFIKSm9zR1lhb0dUdnFiZXhQZEw1dzFpaStRU1E5Tm1nRDZKUk5pRlFoTXNDNDE4YldOMnlpeHJFUU9iVStOQWhZcwpvdGpwSTBpL3YxM0VRUXpKbVJrdk5zZWxNZytiQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRNTVFcGorVUh4ZnBXTjNaU3VWU1ZDcU56TE5UQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVNhbmRwZitnYgp6VFJPeG5tM2V3MkorWVlZcDRpSnZMOUZwWGZwOTREYjd5NHR5UEhsQmtZc3g5VGo4MjFJeThTK2dtK3A2YWFHCmFFMW5Xdzl1MytzemRlbkVFc3p5blFlVkVuSE5PNjdBZ01GcW5UOFIxY2F5Y0lvbHdQK1U4S3h4bDFhdlRISEYKMWRKK1NtN2tIaEo5dE5BQVVLMTYvTnNSbmNtOGFNMmRjaGd5eFBXUEFYZlBaVG0yU01wSFJlUzZmS3hqRTJpeAoyd1hZRmdnbzNtejJYMFJUbFdjWmdWRFdCbFlUblk0YUxjeHh6d1kvc0ZXNExTSmg4T1NLcXd5b1ZEUEtlMFBsCmpYcmtaVjNvKzkyUVc1SjM3T3loYU9ScDNZd1BlMHI4NW9kVVBhN1ZjM1hnbU82K2lScmkvV01VYWxEOU0vSTEKOHNyNjFOUWdvV0QzCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://e54dbb67-9889-4c9c-819d-8ab2e5951934.eu-central-1.linodelke.net:443
  name: lke144715

users:
- name: lke144715-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6Imw2Ylp2MkNsY0tMUWVHelFGMzlpUW5iME1DM2htN2hPVC0yd20xWkQxenMifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4ta2x2NHIiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYzI4NGU1MDItNzRjZC00NzM0LWE0NjYtYzNkM2Q3NzA4MzAyIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.HnhKg-KesC0LZryc5685bnS2GuWJVTQSKLKpHmqvlFtmO4PkxaTPAoLY9CoEuDX7lqueW9noz0d1BUjiTZ3s2p8a7sm5PomZoA2GMUpHZPbiRobLOE5TimnYadcUzVd2dpyEIVC2GmEmMtVt8oCR1DA3lmPRsefLcwNHRn9jMKjFTVpoIs_ZAdRDOpnj9ctW0n4vR30z298fhFZDzkpdhwb8G3My_UyUXdVdwD6DMA6gpcxHQxdYT0_T0Kawhutz-TB4hfNTCa32aOihU14S-cBQzHupcB8RPXMjCJW_e5YXC3PZpEN9YJ63YYXeyp-zJKU-aroEFyvU4nAk7jkqBQ

contexts:
- context:
    cluster: lke144715
    namespace: default
    user: lke144715-admin
  name: lke144715-ctx

current-context: lke144715-ctx
