
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSVpkekJYaXhpd0F3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TXpFeU1EWXhNekV5TkRGYUZ3MHpNekV5TURNeE16RTNOREZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURQcm9UajZxRFF5ZkZMN3A1SWJNV3VoS09TQW5mSUNEelFuTGF6RG5aQ0diMWlZOEkzU2ROK25MQ3EKMVZBT3YrV0ova2J3SW1oaEg3WnZZeVBDY2VFNGRuZjY0bVhud1pOdEljUlIrL2R5NnNHdWV4Y3N3RkF2aFdTaQpmcElmdnJERUZnTDJVdHR1N3hmTkgxYzNEZWRRTHF6cDFjdkUrNVpjVDUyN0NQeTdXZXBORUI1aDRxSjJoclBFCkdQZDVSM25uZ2xpVDR4TEpFSURNTHJ3cEpOOWdiMDlGa3dJU2hJbnZtc3BzUkZmb25COE44MzQ4RDJ5Q1RSMUkKNERLR0xsQ255b05XQldGMjVwVzlpVWZPd1FoN2FZWm9yYm1OdGFBMTd3NnVDY2VRUmJPUm1MaEZtVlNkRDNvbQozUW9aM2VhaWV6cTRnMDhRSzc0V25xQmxJMEtMQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUWkhpTnNoK0FXT0t2SUpYRVNzbEszaUVZUEtEQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQnVkamJrL3BIQwp1emRwdFptZXpiZnNLRWR1UG10OG9TdzNOL0diZC9KdHVNTXl6a2RxaFdGYVhGdFB6bHhTK0wxL3hoYjg3UjBQClp2NDM1eTNQRmwxTE15S010cy9uZUFlb2ZkQ3RXWDBEejV4WHJHMlNvNlRybTdzUkRzZi9IUG9BSFdjbWxueUoKR3RodlpXK1lSYmJUK1BQWlBLRjhiZlhCUzJjNmlJUFp0Wkd3cGRqV0hoQ01sMm82WWtlVzg4RFZJYkcxVFBpLwpwdGhrbG5tcStMMW9DUy83R1p0NWEySzFuc1hoYm43bGZRcEd0a3R5MlhFN3I0Mm5CZ2hEQlZqTDMrVzl3L1dhClR1ZzNKODhkeStXdmxLcVhJb0Z6dS8yenlWTmtPNkRxZUc0S2RDNEdXL2JmbWRSSHNsTDVmTlpuNGxPVUtFOVUKMXl4aHl2Z0FLL2JQCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://ab871e2d-ef65-4d61-94a0-fe14b0158bab.eu-central-2.linodelke.net:443
  name: lke145223

users:
- name: lke145223-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IlRfb0YzYnlaQWFwMGdMZzRycE8zRl9LU3hCb0VsV3YzNHVnNDFXaGtGVm8ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbmN6OW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiZjBmODBlYmEtOWExMy00OGYyLWI1MTEtYTEwNGE0Y2MwYzBlIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.tJn5X3lE8fdkhTQnC14Lg7449ARSWRVEBztHeR9hj_o8921J0AGEkFq-iNjYDNyA9foB51meFWvAnnbg-PR2WmT-S-5ZDARKW_x4IVQf_OzROyrrem9zmCGaqTumABJ5Ccrc1yoPR4j70-hEoaXC4nbwJoP63XWaBcymQjZpnzThZi9umxQYuVUZN57LKvW4vv1GPssS4XX2S5jlLomqCzCbubGNFvhcdgBkiTXsfbNxJu9W2siu2sfZaMkMFZ9RvoykC_s2-Muww4ZkyvSSdiJLyEWFCqdIoTFXVGc__5TkbH4c_ONnKm8NajfMnC8XRiyzOv67r5BSnD-jMsv-Wg

contexts:
- context:
    cluster: lke145223
    namespace: default
    user: lke145223-admin
  name: lke145223-ctx

current-context: lke145223-ctx
