frontend:
  name: frontend
  imagename1: bitnami/git
  imagetag1: 2-debian-10
  imagename2: httpd
  imagetag2: 2.4
  volume: website-data
  port: 8080
  replica: 2
  apiPort: 4567
  service: mboard-api-service
