name: "Infrastructure Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  Infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 