apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: "{{ .Values.frontend.name }}-service"
      port:
        number: {{ .Values.frontend.port}}
  rules:
    - http:
        paths: 
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.frontend.service }}
                port:
<<<<<<< HEAD
                  number: {{ .Values.frontend.apiPort }}
=======
                  number: {{ .Values.frontend.apiPort }}
          - path: /argocd/
            pathType: Prefix
            backend:
              service:
                name: argocd-server-external
                port:
                  number: {{ .Values.frontend.argoport }}
                namespace: argocd 
>>>>>>> ad681af6bd7b7a05066d76cd4f0fe905f5f7c65d
