apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.frontend.name }}-service"
spec:
  selector:
    component: {{ .Values.frontend.name }}
  ports:
    - port: {{ .Values.frontend.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-server-external
spec:
  type: ExternalName
  externalName: argocd-server.argocd.svc.cluster.local
  ports:
    - port: 8080