apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: messageboard-api
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maxhaeger/message-board-api
    targetRevision: main
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default
